use proyectoBD1;
insert into Proveedor(id_proveedor, name, telefono, email, direccion ) values(1, "Pollo norteño", "35523241","nortea@gmail.com","Tegucigalpa, tizatillo");
insert into Proveedor(id_proveedor, name, telefono, email, direccion ) values(2, "Leyde", "54325672","ley@gmail.com","SPS, Barrio Guamilito");
insert into Proveedor(id_proveedor, name, telefono, email, direccion ) values(3, "Sula","53532145","sul@gmail.com","SPS, Barrio medina");
insert into Proveedor(id_proveedor, name, telefono, email, direccion ) values(4, "Lactosa", "563533421","lact@gmail.com","Puerto Cortes, Col san Ignacio");
insert into Proveedor(id_proveedor, name, telefono, email, direccion ) values(5, "Coca cola", "23456723","cocafd@gmail.com","La ceiba, centro");
insert into Proveedor(id_proveedor, name, telefono, email, direccion ) values(6, "Pepsi", "532324163","pep12@gmail.com","SPS, medina");
insert into Proveedor(id_proveedor, name, telefono, email, direccion ) values(7, "Carnes San Miguel", "876456723","smiguefd@gmail.com","Siguatepeque, los terrones");
insert into Proveedor(id_proveedor, name, telefono, email, direccion ) values(8, "Camar", "76656723","camrd@gmail.com","SPS");
insert into Proveedor(id_proveedor, name, telefono, email, direccion ) values(9, "Coapigor", "53421345","coapi@gmail.com","Tegucigalpa");
insert into Proveedor(id_proveedor, name, telefono, email, direccion ) values(10, "La rosa", "98766723","larofd@gmail.com","Comayagua");
insert into Proveedor(id_proveedor, name, telefono, email, direccion ) values(11, "Panaderia tabora", "12346723","tab@gmail.com","Danli,barrio abajo");
insert into Proveedor(id_proveedor, name, telefono, email, direccion ) values(12, "Salmans", "34346278","salmsfd@gmail.com","Tegucigalpa");
insert into Proveedor(id_proveedor, name, telefono, email, direccion ) values(13, "DeliPan", "64534236","delpd@gmail.com","Comayagua");
insert into Proveedor(id_proveedor, name, telefono, email, direccion ) values(14, "Lipton", "65655253","telip@gmail.com","SPS, 6 avenida");
insert into Proveedor(id_proveedor, name, telefono, email, direccion ) values(15, "Carnes y mas", "54646343","carnm@gmail.com","Siguatepeque, barrio guadalupe");
insert into Proveedor(id_proveedor, name, telefono, email, direccion ) values(16, "delicia", "98453627","deli@gmail.com","Puerto cortes, col cabañas");
insert into Proveedor(id_proveedor, name, telefono, email, direccion ) values(17, "popular", "65443327","popu14@gmail.com","Comayagua, barrio el centro");
insert into Proveedor(id_proveedor, name, telefono, email, direccion ) values(18, "verduras el sembrador", "552434612","vsembra@gmail.com","Fco Morazan,Sabana grande");
insert into Proveedor(id_proveedor, name, telefono, email, direccion ) values(19, "greenfresh", "23456723","jgreenco@gmail.com","Choluteca, col concepcion");
insert into Proveedor(id_proveedor, name, telefono, email, direccion ) values(20, "Heallmanns", "85756453","hell&co@gmail.com","SPS, Col las brisas");
insert into Proveedor(id_proveedor, name, telefono, email, direccion ) values(21, "CampoFresco", "23465778","campofr@gmail.com","Tegucigalpa, Col Palmira");
insert into Proveedor(id_proveedor, name, telefono, email, direccion ) values(22, "Suli", "87453426","sulh@gmail.com","Omoa, Barrio Barahona");
insert into Proveedor(id_proveedor, name, telefono, email, direccion ) values(23, "Agrosal", "4566453","arol@gmail.com","Danli, Col las colinas");
insert into Proveedor(id_proveedor, name, telefono, email, direccion ) values(24, "unilever", "23465778","unile@gmail.com","Tegucigalpa, Col miraflores");
insert into Proveedor(id_proveedor, name, telefono, email, direccion ) values(25, "industrial de alimentos", "74859692","industriala@gmail.com","Tegucigalpa");
insert into Proveedor(id_proveedor, name, telefono, email, direccion ) values(26, "Diprocom", "75896321","diprocom@gmail.com","Tegucigalpa, el porvenir");
insert into Proveedor(id_proveedor, name, telefono, email, direccion ) values(27, "Dcasa", "12487557","dcasa@gmail.com","Amarateca");
insert into Proveedor(id_proveedor, name, telefono, email, direccion ) values(28, "Dinant", "77854965","dinant@gmail.com","Tegucigalpa, barrio morazan");
insert into Proveedor(id_proveedor, name, telefono, email, direccion ) values(29, "EYL comercial", "85796547","eylcom@gmail.com","Tegucigalpa, san rafael");
insert into Proveedor(id_proveedor, name, telefono, email, direccion ) values(30, "Industria carnica", "75876985","icarnica@gmail.com","Tegucigalpa, la Kennedy");
insert into Proveedor(id_proveedor, name, telefono, email, direccion ) values(31, "Distribbuidora istmania", "24589637","itsmania@gmail.com","Tegucigalpa, la cañada");
insert into Proveedor(id_proveedor, name, telefono, email, direccion ) values(32, "Dialca", "25454879","dialca@gmail.com","Tegucigalpa");
insert into Proveedor(id_proveedor, name, telefono, email, direccion ) values(33, "Delikatessen", "36698875","delikatessen@gmail.com","Tegucigalpa, alameda");
insert into Proveedor(id_proveedor, name, telefono, email, direccion ) values(34, "inprova", "47589657","inprova@gmail.com","Gracias a Dios, puerto lempira");
insert into Proveedor(id_proveedor, name, telefono, email, direccion ) values(35, "Nestle", "57899658","nestle@gmail.com","La ceiba");
insert into Proveedor(id_proveedor, name, telefono, email, direccion ) values(36, "Supermercado YIP", "47859658","syip@gmail.com","Tegucigalpa, el prado");
insert into Proveedor(id_proveedor, name, telefono, email, direccion ) values(37, "Carnicos caribe", "67895321","carnicosc@gmail.com","SPS, ave. juan pablo");
insert into Proveedor(id_proveedor, name, telefono, email, direccion ) values(38, "productos montecristo", "78546963","pmontecristo@gmail.com","SPS");
insert into Proveedor(id_proveedor, name, telefono, email, direccion ) values(39, "Supermercado Mas por menos", "47777859","maspormenos@gmail.com","La ceiba, el centro");
insert into Proveedor(id_proveedor, name, telefono, email, direccion ) values(40, "Lacteos hernandez", "47855555","lhernandez@gmail.com","Olancho, catacamas");
insert into Proveedor(id_proveedor, name, telefono, email, direccion ) values(41, "Carniceria florida", "25585896","cflorida@gmail.com","Choluteca,marcovia");
insert into Proveedor(id_proveedor, name, telefono, email, direccion ) values(42, "Leoplast", "88859688","leoplast@gmail.com","Comayagua,las lajas");
insert into Proveedor(id_proveedor, name, telefono, email, direccion ) values(43, "Codilsa", "35488757","codilsa@gmail.com","Siguatepeque,col.boquin");
insert into Proveedor(id_proveedor, name, telefono, email, direccion ) values(44, "Panaderia suiza", "75855559","psuiza@gmail.com","la paz, palomar");
insert into Proveedor(id_proveedor, name, telefono, email, direccion ) values(45, "Diapa", "57888897","diapa@gmail.com","SPS");
insert into Proveedor(id_proveedor, name, telefono, email, direccion ) values(46, "Digral", "88875848","digral@gmail.com","valle,nacaome");
insert into Proveedor(id_proveedor, name, telefono, email, direccion ) values(47, "MAYAB", "66588996","mayab@gmail.com","Tegucigalpa,las torres");
insert into Proveedor(id_proveedor, name, telefono, email, direccion ) values(48, "Distribuidora san jose", "22554477","dsanjose@gmail.com","Colon,las flores");
insert into Proveedor(id_proveedor, name, telefono, email, direccion ) values(49, "DIMO", "55588763","dimo@gmail.com","Siguatepeque, los pinos");
insert into Proveedor(id_proveedor, name, telefono, email, direccion ) values(50, "El molinar", "99785696","molinard@gmail.com","SPS");

select * from Proveedor;